### ISSUE TITLE
"GenAI API key is missing." with AmazonBedrock configured

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/editor-extensions#553]
I am running with AmazonBedrock and I see a warning "GenAI API key is missing".
Note I ignored this warning and was able to proceed and saw Kai talk to Bedrock and get a code suggestions

```
 AmazonBedrock: &active
    environment:
      AWS_ACCESS_KEY_ID: "REDACTED"
      AWS_SECRET_ACCESS_KEY: "REDACTED"
      AWS_DEFAULT_REGION: "us-east-1"
    provider: ChatBedrock
    args:
      model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"

      ## Following keys are optional & only exist for documentation purposes
      # temperature: <number>
      # additionalModelRequestFields: <object>
      # configFilepath: <string>
```
* Example of file, note I REDACTED the actual keys, but when I ran I had valid keys in:  https://gist.github.com/jwmatthews/de42992415245803cd3bd5cabcc56cf0

<img width="1349" alt="Image" src="https://github.com/user-attachments/assets/5a05afdf-5792-4b8e-b77f-81150be7d0b8" />

Yet notice, kai is working with LLM
<img width="1159" alt="Image" src="https://github.com/user-attachments/assets/c2da7952-4cfe-4ebb-87e3-6c8be2aa03e8" />
