### ISSUE TITLE
[.github] workflow to handle creating a release whenever a `vX.Y.Z` tag is created

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#73]
Similar to what we did [here for container images being pushed to quay](https://github.com/konveyor/operator/blob/main/.github/workflows/march-image-build-push.yml), when we see a tag of the `vx.y.z` form we should find the release associated with it and add the vscode extension package(s) to it as assets.

Pseudocode:

```
name: Publish extension package(s)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    steps:
      - checkout code + setup node
      - update package.json version to match the tag (it should win now that we are setting it)
      - get the artifacts and rename them
      - find the release (because we are assuming it's creation is what made the semver compliant tag exist)
      - add artifacts to the release
```
